### PR TITLE
issue substitution evaluation when returns error

### PR DESCRIPTION
**Pull request by adrianiftode**

### CODE REVIEW

**Comment by GeorgDangl** [comment]
Is this ready for merging? I only see an added test, and a change in a test assetion.

**Comment by adrianiftode** [comment]
This is not for merging, it contains only the test to explain what I think could be an issue. If this is an issue, I can continue to on the fix.

**Comment by GeorgDangl** [comment]
Ah, thank you! Let's keep it open then, I'll try to look at it.

**Comment by GeorgDangl** [comment]
I just checked, we've got that covered in the README: https://github.com/GeorgDangl/Dangl.Calculator/blob/dev/README.md#substitutions

    If duplicates in substitutions are present, the calculator will request each one individually.

So I think if there's ever an edge case where an impure function is used for resolving, it should be cached at the caller level.

**Pull request closed without merging**
